### ISSUE TITLE
Method `projects.delete` returns 'Unsupported Media Type'

### ISSUE THREAD

**Issue by mamercad** [digitalocean/pydo#158]
Not sure this is the right place to file this (let me know).

Test program:

```python
import os
from azure.core.exceptions import HttpResponseError
from pydo import Client

client = Client(token=os.getenv("DIGITALOCEAN_TOKEN"))
project_id = "e4654ba2-ebd5-4405-b6be-af13047568ef"

try:
    project = client.projects.get(project_id=project_id)
    print(project)
except HttpResponseError as err:
    raise

try:
    client.projects.delete(project_id=project_id)
except HttpResponseError as err:
    raise
```

Output:

```shell
❯ python3 t.py
{'project': {'id': 'e4654ba2-ebd5-4405-b6be-af13047568ef', 'owner_uuid': '3281ad3a-0092-4e6b-abd2-c7a7ed211503', 'owner_id': 10112447, 'name': 'my-web-api', 'description': 'My Website API', 'purpose': 'Service or API', 'environment': 'Production', 'is_default': False, 'created_at': '2023-01-20T03:28:38Z', 'updated_at': '2023-01-20T03:28:38Z'}}
Traceback (most recent call last):
  File "/Users/mark/t.py", line 15, in <module>
    client.projects.delete(project_id=project_id)
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/x-tgVTt8yo-py3.9/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/x-tgVTt8yo-py3.9/lib/python3.9/site-packages/pydo/operations/_operations.py", line 93609, in delete
    raise HttpResponseError(response=response)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Unsupported Media Type'
```

**Comment by danaelhe** [comment]
Thanks for opening this up. The API is expecting a json body for some reason. The work around would be to do something like this:
   
```
 # test deleting a project
    # Work around endpoint requiring "application/json" for DELETES even though
    # there is no request or response body.
    custom_headers = {"Content-Type": "application/json"}
    delete_resp = integration_client.projects.delete(
        headers=custom_headers, project_id=project_id
    )
```

We're going to look into a way to inject this header automatically within the client, but for now here's a work around.
