### ISSUE TITLE
Error: invalid checksum digest format.

### ISSUE THREAD

**Issue by hector-medina-nubosas** [digitalocean/pydo#178]
Hello community!

I'm using PyDO for cleaning a Container Registry in DigitalOcean so we fit under our plan without spending extra credits. 

When trying to delete an image from its manifest with the `delete_repository_manifest()` method, I'm getting the following error:

> Traceback (most recent call last):
  File "/...../pydo/do.py", line 36, in <module>
    client.registry.delete_repository_manifest(registry, repositories[0],response['manifests'][0]['digest'])
  File "/...../pydo/venv/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/...../pydo/venv/lib/python3.11/site-packages/pydo/operations/_operations.py", line 112200, in delete_repository_manifest
    raise HttpResponseError(response=response)
azure.core.exceptions.HttpResponseError: (None) invalid digest: invalid checksum digest format
Code: None
Message: invalid digest: invalid checksum digest format

I have checked the digest hash value and it's the same I'm trying to delete. According to the API docs: 

> The manifest digest of a container registry repository tag.
https://docs.digitalocean.com/reference/api/api-reference/#operation/registry_delete_repositoryManifest

This is the first time for me to use this library, so I might be doing something wrong too.

Thanks in advance.

----

Update:

As an update, I have tried to use the DigitalOcean HTTP API itself to delete the resource. I could delete it without any problem with the API. I have used the same parameters I'm sending to the `delete_repository_manifest()`, so it's definitely a bug.

**Comment by danaelhe** [comment]
Hi there,

Thanks for the write up- we will investigate further on our end and give an update here when we can.
